apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: dhna871li-python 
  janus-idp.io/tekton: dhna871li-python
  backstage.io/kubernetes-id: dhna871li-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dhna871li-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml