apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dhna871li-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dhna871li-python 
  name: dhna871li-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dhna871li-python 
